#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Include Custom local configuration (Should not tracked in preztos repo)
if [[ -s "${ZDOTDIR:-$HOME}/.zshrc.local" ]]; then
	source "${ZDOTDIR:-$HOME}/.zshrc.local"
fi

# User local functions
fpath+=~/.zfunc

# Customize to your needs...
setopt Interactivecomments
